#!/usr/bin/env python3
"""Structured parameterized reconstruction actions for Dynamic Cue Retrieval."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ParameterizedEvidenceAction:
    """
    Structured reconstruction action generated by the cue module.
    """

    type: str  # query_rewrite | entity_expand | temporal_expand | session_expand | hybrid
    target_requirement: str = ""
    anchors: List[str] = field(default_factory=list)
    query: str = ""
    retrieval_view: str = "text"  # text | entity | time | session | text_time | hybrid
    top_k: int = 8
    source_memory_ids: List[str] = field(default_factory=list)
    confidence: float = 0.0
    hypothesis_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "ParameterizedEvidenceAction":
        return cls(
            type=str(d.get("type") or d.get("operation") or "query_rewrite"),
            target_requirement=str(d.get("target_requirement") or ""),
            anchors=[str(a) for a in (d.get("anchors") or [])],
            query=str(d.get("query") or ""),
            retrieval_view=str(d.get("retrieval_view") or "text"),
            top_k=int(d.get("top_k") or 8),
            source_memory_ids=[str(x) for x in (d.get("source_memory_ids") or [])],
            confidence=float(d.get("confidence") or 0.0),
            hypothesis_id=str(d.get("hypothesis_id") or ""),
        )

    def to_key(self) -> str:
        return f"{self.type}|{self.retrieval_view}|{self.query[:80]}|{','.join(self.anchors[:3])}"
